# CONFIG SETUP
alluka_explain_config: "alluka_zoldyck"

bot_token: "1339785992:AAFJKy5-UmmcYi5-8YJjCHLB6toIhEgHnAM"  
owner_id: 1188642691
api_key: 1438627
api_hash: 'a3df45b8d3b710a5b15b485381f1adc8'
owner_username: "Ayanokoji_op"
database_url: "postgres://zsyltgjf:gnr9oSdXglJfT-A26-2N7WeNW1uLNHX_@hansken.db.elephantsql.com:5432/zsyltgjf"
message_dump: "chat_id"
gban_dump: "chat_id"
load: []
no_load: []
cert_path: None
port: 5000
workers: 4
webhook: False
url: None
allow_excl: False
del_cmds: False
strict_gban: False
strict_gmute: False
spammers_lists: [100]
ban_sticker: 'CAACAgQAAxkBAAEGD2ZfX6zRvoCogPWDrCO9RdYa46wy4gACYAEAAix7cAqLRN5ebbj1DxsE'


# API SETUP
cash_api: None  
time_api: None  
wall_api: None
lydia_api: None
sw_api: None

# Zoldyck family config
alluka: []
hisoka: [905126640]
ging: []
shizuku: []
silva: []
gon: [] 
illumi: []
leorio: []
biscuit: []
chrollo: []
killua: [943978681] 
meruem: [] 
kite: [] 

# Permission
dev_users: []
sudo_users: [905126640, 943978681]
support_users: []
whitelist_users: []
