# CONFIG SETUP
alluka_explain_config: "alluka_zoldyck"

bot_token: "1340938209:AAE0wXintJ29dtT37zly7febTQQKJGWvoQw"  
owner_id: 943978681
api_key: 1438627
api_hash: 'a3df45b8d3b710a5b15b485381f1adc8'
owner_username: "Ayanokoji_op"
database_url: "postgres://zsyltgjf:gnr9oSdXglJfT-A26-2N7WeNW1uLNHX_@hansken.db.elephantsql.com:5432/zsyltgjf"
message_dump: "chat_id"
gban_dump: "chat_id"
load: []
no_load: []
cert_path: None
port: 5000
workers: 4
webhook: False
url: None
allow_excl: False
del_cmds: False
strict_gban: False
strict_gmute: False
spammers_lists: [100]
ban_sticker: 'CAACAgUAAxkBAAIHsl5nbqXdDTmpG2HFDNhnwvE5kFbWAAI9AQAC3pTNLzeTCUmnhTneGAQ'


# API SETUP
cash_api: None  
time_api: None  
wall_api: None
lydia_api: None
sw_api: None

# Zoldyck family config
alluka: [936828744]
hisoka: [680240877]
ging: [239508098]
shizuku: [516449930]
silva: [331863490]
gon: [123456789] 
illumi: [854853029]
leorio: [575737330]
biscuit: [586760757]
chrollo: [806845434]
killua: [165822682] 
meruem: [696086626] 
kite: [604968079] 

# Permission
dev_users: [1256676137]
sudo_users: [1256676137, 802002142, 680240877, 604968079]
support_users: []
whitelist_users: []
