# CONFIG SETUP
alluka_explain_config: "alluka_zoldyck"

bot_token: "1339785992:AAFJKy5-UmmcYi5-8YJjCHLB6toIhEgHnAM"  
owner_id: 943978681
api_key: 1438627
api_hash: 'a3df45b8d3b710a5b15b485381f1adc8'
owner_username: "Ayanokōji_op"
database_url: "postgres://zsyltgjf:gnr9oSdXglJfT-A26-2N7WeNW1uLNHX_@hansken.db.elephantsql.com:5432/zsyltgjf"
message_dump: "-1001272685653"
gban_dump: "-1001272685653"
load: []
no_load: []
cert_path: None
port: 5000
workers: 4
webhook: False
url: None
allow_excl: False
del_cmds: False
strict_gban: False
strict_gmute: False
spammers_lists: [100]
ban_sticker: 'CAACAgUAAxkBAAEGFsZfYw2yKu36GeDqHm4bnPQU_lhi9gACOgAD8CLzNdyuxbDUE74oGwQ'


# API SETUP
cash_api: None  
time_api: None  
wall_api: c3650ba964034e8539cf0b4bcfb03df6
lydia_api: 8d765d18ec4abe297261205a0a96491c25d544223e39fde056d29054ebfcec71c7d97bf10a062287c5b26bb33fb6fb31b92c9085be40cc28b8b96b3c2f83d70f
sw_api: ~WGXQD0h0qMhv7jtGsxYXSDQP7zwgIwLXpbVuuAH2BrFjjxYTXEnlOO8NXRZfCfn

# Zoldyck family config
alluka: []
hisoka: [905126640]
ging: []
shizuku: []
silva: []
gon: [] 
illumi: []
leorio: []
biscuit: []
chrollo: []
killua: [1188642691] 
meruem: [] 
kite: [] 

# Permission
dev_users: []
sudo_users: [905126640]
support_users: []
whitelist_users: []
